In [1]:
import numpy as np 
 

In [5]:
a1 = np.array([1, 2, 3, 4, 5])
a1

array([1, 2, 3, 4, 5])

In [7]:
a1.size

5

In [8]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([1, 2, 3, 4.0, 5.0])
a2

array([1., 2., 3., 4., 5.])

In [15]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [18]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
a1 = np.arange(0, 10)
a1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [23]:
m = np.arange(0, 20).reshape(5, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
np.size(m)

20

In [26]:
np.size(m, 0)

5

In [28]:
np.size(m , 1
       )

4

In [40]:
m[:, 2]

array([ 2,  6, 10, 14, 18])

In [43]:
a = np.arange(5)
a<2

array([ True,  True, False, False, False])

In [47]:
a

array([0, 1, 2, 3, 4])

In [48]:
def exp (x):
    return x<3 or x>3

In [54]:
np.vectorize(exp)(a)

array([ True,  True,  True, False,  True])

In [55]:
r = a < 3

In [56]:
np.sum(a < 3)

3

In [58]:
a1 = np.arange(0, 5)
a2 = np.arange(5, 0, -1)

In [59]:
a1

array([0, 1, 2, 3, 4])

In [60]:
a2

array([5, 4, 3, 2, 1])

In [61]:
a1 = np.arange(9).reshape(3, 3)
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
a1 = np.arange(9).reshape(3, 3)
a2 = np.arange(9, 0 , -1).reshape(3, 3)
a1 < a2

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [63]:
a1 = np.arange(1, 10)
a1[3:8]

array([4, 5, 6, 7, 8])

In [64]:
a1[::2]

array([1, 3, 5, 7, 9])

In [65]:
a1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [69]:
m[:,1:3]
m[[1,3,4],:]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [71]:
a = np.arange(0, 9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
m = a.reshape(3, 3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
raveled = m.ravel()
raveled

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
reshaped = m.reshape(np.size(m))
raveled = m.ravel()

In [79]:
reshaped

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
raveled

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
m2 = np.arange(0, 9).reshape(3,3)
m2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
flattened = m2.flatten()
flattened 

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
flattened.shape = (3, 3)
flattened


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
flattened.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [90]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
b = (a + 1) * 10
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [94]:
np.hstack((a,b))

array([[ 0,  1,  2, 10, 20, 30],
       [ 3,  4,  5, 40, 50, 60],
       [ 6,  7,  8, 70, 80, 90]])

In [96]:
np.concatenate((a, b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [97]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [98]:
np.dstack((a,b))

array([[[ 0, 10],
        [ 1, 20],
        [ 2, 30]],

       [[ 3, 40],
        [ 4, 50],
        [ 5, 60]],

       [[ 6, 70],
        [ 7, 80],
        [ 8, 90]]])

In [99]:
one_d_a = np.arange(5)
one_d_a

array([0, 1, 2, 3, 4])

In [100]:
one_d_b = (one_d_a + 1) * 10
one_d_b

array([10, 20, 30, 40, 50])

In [102]:
np.row_stack((one_d_a, one_d_b))

array([[ 0,  1,  2,  3,  4],
       [10, 20, 30, 40, 50]])

In [103]:
m = np.arange(10, 19).reshape(3, 3)

In [104]:
m

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [106]:
print (m)
print ("{0} min of the entire matrix".format(m.min()))
print ("{0} max of entire matrix".format(m.max()))
print ("{0} position of the min value".format(m.argmin()))
print ("{0} position of the max value".format(m.argmax()))
print ("{0} mins down each column".format(m.min(axis = 0)))
print ("{0} mins across each row".format(m.min(axis = 1)))
print ("{0} maxs down each column".format(m.max(axis = 0)))
print ("{0} maxs across each row".format(m.max(axis = 1)))

[[10 11 12]
 [13 14 15]
 [16 17 18]]
10 min of the entire matrix
18 max of entire matrix
0 position of the min value
8 position of the max value
[10 11 12] mins down each column
[10 13 16] mins across each row
[16 17 18] maxs down each column
[12 15 18] maxs across each row


In [108]:
a = np.arange(10)

In [109]:
a.mean(), a.std(), a.var()

(4.5, 2.8722813232690143, 8.25)

In [112]:
a = np.arange(1, 6)
a.sum(), a.prod()

(15, 120)

In [113]:
a.cumsum(), a.cumprod()

(array([ 1,  3,  6, 10, 15]), array([  1,   2,   6,  24, 120]))

In [118]:
a = np.arange(10)
(a < 5).any()

True

In [120]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [121]:
np.arange(10).reshape(2,5).ndim

2